// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKBpza4s9_0_TK_CK0G6jx0Yj4RI3BXgE',
    appId: '1:827992378371:web:63c971027d271f7bb99236',
    messagingSenderId: '827992378371',
    projectId: 'act12-2e518',
    authDomain: 'act12-2e518.firebaseapp.com',
    storageBucket: 'act12-2e518.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC13ucgqlsUarwIa-QdZzW3uYJ1uIVbUi8',
    appId: '1:827992378371:android:702c1a19f6cda534b99236',
    messagingSenderId: '827992378371',
    projectId: 'act12-2e518',
    storageBucket: 'act12-2e518.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2Xq0-LG8vguZD5U-uv-uPKSx8fS7yfZw',
    appId: '1:827992378371:ios:2146d6c90b0822fab99236',
    messagingSenderId: '827992378371',
    projectId: 'act12-2e518',
    storageBucket: 'act12-2e518.firebasestorage.app',
    iosBundleId: 'com.example.cw6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2Xq0-LG8vguZD5U-uv-uPKSx8fS7yfZw',
    appId: '1:827992378371:ios:2146d6c90b0822fab99236',
    messagingSenderId: '827992378371',
    projectId: 'act12-2e518',
    storageBucket: 'act12-2e518.firebasestorage.app',
    iosBundleId: 'com.example.cw6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKBpza4s9_0_TK_CK0G6jx0Yj4RI3BXgE',
    appId: '1:827992378371:web:4e1d0d3fd154016eb99236',
    messagingSenderId: '827992378371',
    projectId: 'act12-2e518',
    authDomain: 'act12-2e518.firebaseapp.com',
    storageBucket: 'act12-2e518.firebasestorage.app',
  );
}
